### ISSUE TITLE
state page links not redirecting to target=_blank in customizer

### ISSUE THREAD

**Issue by DanielJWood** [nprapps/elections24-general#312]
In particular, if you click the `county-level results` or `all house results`

**Comment by alykat** [comment]
Ooh, actually the bug is more subtle than that for those state page links.

If the URL params include "embedded," that should carry over to those links so they open in the same window, in embedded mode / without the rest of the page furniture. It's ok if those particular results open in the same window (same result if you click on "house" or "president" from the nav at the top).
